version: 2
registries:
  public-nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: nuget
    directory: "/"
    registries:
      - public-nuget
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 15
    ignore:
      - dependency-name: "Google.Protobuf"
    groups:
      AspNetCoreHealthChecks:
        patterns:
          - "AspNetCore.HealthChecks*"
      AspNetCore:
        patterns:
          - "Microsoft.AspNetCore*"
      MicrosoftExtensions:
        patterns:
          - "Microsoft.Extensions*"
      EntityFrameworkCore:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      OpenTelemetry:
        patterns:
          - "OpenTelemetry*"
      MicrosoftDotNet:
        patterns:
          - "Microsoft.DotNet*"
      Grpc:
        patterns:
          - "Grpc.*"
      Polly:
        patterns:
          - "Polly.*"
      Serilog:
        patterns:
          - "Serilog*"
      Tests:
        patterns:
          - "Microsoft.NET.Test*"
          - "xunit*"
      Fluent:
        patterns:
          - "Fluent*"
      All:
        patterns:
          - "*"
    labels:
      - "area-codeflow"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - area-engineering-systems
